name: Benchmark Test
on:
  workflow_dispatch:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: [self-hosted, linux, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Benchmark Test
        run: |
          echo "This job runs on a self-hosted runner!"
          echo "Running benchmark test..."
          python3 benchmark/benchmodulellm.py